#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXGLIBADV = ../../$(GLIBADV)
EXSNAPADV = ../../$(SNAPADV)
EXSNAPEXP = ../../$(SNAPEXP)

INSTALL_PATH = /usr/local/lib

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  #CXXFLAGS += -ggdb
  # turn on for OpenMP
  CXXOPENMP = 
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall -Wno-unknown-pragmas
  CXXFLAGS += -O3 -DNDEBUG
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifeq ($(CLANG), clang)
    CXXFLAGS += -DNOMP
    CXXOPENMP =
  else ifeq ($(CLANG), LLVM)
    CXXFLAGS += -DNOMP
    CXXOPENMP =
  else
    CXXFLAGS += -fopenmp
    #CXXOPENMP += -fopenmp
  endif
  ifeq ($(IOS_BUILD), 1)
    CXXFLAGS += -arch arm64 -fembed-bitcode=all -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -D GLib_IOS -mfpu=neon-fp16 -mfloat-abi=hard 
  endif
  ifeq ($(TVOS_BUILD), 1)
    CXXFLAGS += -arch arm64 -fembed-bitcode=all -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk -mtvos-version-min=11.2 -D GLib_IOS -mfpu=meon-fp16 -mfloat-abi=hard
  endif
  LDFLAGS +=
  LIBS +=

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif

ifeq ($(ANDROID_BUILD), 1)
    export API=21
    CC = /Applications/Unity/Hub/Editor/2019.4.3f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android28-clang++
    AR = /Applications/Unity/Hub/Editor/2019.4.3f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ar
    RANLIB = /Applications/Unity/Hub/Editor/2019.4.3f1/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android-ranlib
    CXXFLAGS += -mfpu=neon-fp16 -mfloat-abi=hard
endif
